swagger: '2.0'
info:
  description: "API desenvolvida para o processo seletivo da RedVentures"
  version: 1.0.0
  title: Widget API
  contact:
    email: guilherme.artem@gmail.com
host: localhost:4000
basePath: /
tags:
  - name: login
    description: Login Operation
  - name: user
    description: Operations about user
  - name: widget
    description: Everything about your Widgets
schemes:
  - http
paths:
  /login:
    post:
      tags:
        - login
      summary: Login into application
      description: 'Use username as user and password as password'
      operationId: login
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Widget object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/Login'
      responses:
        default:
          description: successful operation
          schema:
            $ref: '#/definitions/Token'
  /users:
    get:
      tags:
        - user
      summary: Get all users
      description: ''
      security:
        - Bearer: []
      operationId: getUsers
      produces:
        - application/json
      responses:
        default:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
  '/users/{id}':
    get:
      tags:
        - user
      summary: Get user by user id
      description: ''
      security:
        - Bearer: []
      operationId: getUserByID
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: 'The id of the user that needs to be fetched.'
          required: true
          type: integer
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/User'
        '404':
          description: User not found
  /widgets:
    get:
      tags:
        - widget
      summary: Get all widgets
      description: ''
      security:
        - Bearer: []
      operationId: getWidgets
      produces:
        - application/json
      responses:
        default:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Widget'
    post:
      tags:
        - widget
      summary: Add a new widget
      description: ''
      security:
        - Bearer: []
      operationId: addWidget
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Widget object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/Widget'
      responses:
        '200':
          description: successful operation
        '400':
          description: bad request - missing fields
        '422':
          description: unprocessable entity
  '/widgets/{id}':
    get:
      tags:
        - widget
      summary: Get widget by id
      description: ''
      security:
        - Bearer: []
      operationId: getWidgetByID
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: 'The id of the widget that needs to be fetched.'
          required: true
          type: integer
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Widget'
        '404':
          description: widget not found
    put:
      tags:
        - widget
      summary: Update widget by id
      description: ''
      security:
        - Bearer: []
      operationId: updateWidgetByID
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: 'The id of the widget that needs to be updated.'
          required: true
          type: integer
        - in: body
          name: body
          description: Widget object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/Widget'
      responses:
        '204':
          description: successful operation
        '404':
          description: widget not found
        '422':
          description: unprocessable entity
securityDefinitions:
   Bearer:
      type: apiKey
      name: Authorization
      in: header
definitions:
  Login:
    type: object
    required:
      - username
      - password
    properties:
      username:
        type: string
      password:
        type: string
  Token:
    type: object
    properties:
      token:
        type: string
  User:
    type: object
    required:
      - id
      - name
      - gravatar
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      gravatar:
        type: string
  Widget:
    type: object
    required:
      - id
      - name
      - color
      - price
      - inventory
      - melts
    properties:
      id:
        type: integer
      name:
        type: string
      color:
        type: string
      price:
        type: number
        format: string
      inventory:
        type: integer
      melts:
        type: boolean
externalDocs:
  description: Github
  url: 'https://goo.gl/2UPDrE'
